### ISSUE TITLE
Tiny Kanji conversion miskate in gobject-introspection/introduction.md

### ISSUE THREAD

**Issue by okkez** [RubyData/workshop-materials#1]
https://github.com/RubyData/workshop-materials/blob/master/gobject-introspection/introduction.md の776行目あたりで

> 実行してクラッシュせずに清浄すれば問題ありません。

と書いてあるところは

> 実行してクラッシュせずに正常終了すれば問題ありません。

と書こうとして間違えたのでしょうか？
Pull Requestにできるほど自信が持てなかったので報告させてもらいました。

**Comment by kou** [comment]
その通りですね！
修正しました。

**Comment by okkez** [comment]
Thanks!
